### PR TITLE
Fix jsonrpc client

### PR DESCRIPTION
**Pull request by binocarlos**
The latest version of `jsonrpcclient.clients.http_client` requires us to access `res.data.result` to extract the actual data returned [as documented here](https://jsonrpcclient.readthedocs.io/en/latest/api.html)

This PR returns `res.data.result` wherever we are using the jsonrpc client

### CODE REVIEW

**Comment by lukemarsden** [comment]
Can you declare the dependency with the new API explicitly?

**Comment by lukemarsden** [comment]
Ah, we do already: https://github.com/dotmesh-io/python-sdk/blob/master/setup.py#L24

**Comment by lukemarsden** [comment]
LGTM, and you've tested this and it works?

**Review by prisamuel — APPROVED** [review]
LGTM

**Comment by binocarlos** [comment]
Yeah did a bunch of manual testing and ran the test script Michael had included :+1:

**Comment by lukemarsden** [comment]
btw, I don't think you need `.data.result` on requests where you're throwing away the response (i.e. not returning it or assigning it to a variable)

**Comment by lukemarsden** [comment]
maybe just make a followup issue to tidy that up

**Pull request merged**
